config/routes.rb
Rails.application.routes.draw do
  root "main#home"
  get '/about',to: "main#about"

  get "/login", to: "sessions#new"
  get "/logout", to: "sessions#destroy"
  post "/sessions", to: "sessions#create"

  resources :users do
    resources :questions, except: [:new, :index]
    get "/unanswered_questions", to: "questions#unanswered_questions"
    # resources :questions
  end

  post "/contact_us", to: "main#contact_us"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  validates :question, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  has_secure_password
  has_many :questions

  def self.confirm(params)
    @user = User.find_by({email: params[:email]})
    @user ? @user.authenticate(params[:password]) : false
  end

  def full_name
    self.first_name + " " + self.last_name
  end

end

app/controllers/application_controller.rb
require "simply_paginate"
require "addressable/template"

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper
  include SimplyPaginate
  include Addressable
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
  end

  def about
  end

  def contact_us
    UserMailer.contact_us(email_params).deliver_now
    redirect_to root_path
  end

  private
  def email_params
    params.require(:email).permit(:first_name,:last_name,:email,:message)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_user, only: [:unanswered_questions, :create]

  # this will be the access point to unanswered questions
  def unanswered_questions
    if is_signed_in? @user
      @page_number = params[:page].nil? ? 1 : params[:page].to_i
      @unanswered_questions = @user.questions.where(answer: nil)
      @pages = Paginator.new(@unanswered_questions, 5)
      @page = @pages[ @page_number ]

      @page = @page ? @page.elements : []
      @url = Addressable::Template.new("#{user_unanswered_questions_path(@user)}{?page}")

    else
      flash[:error] = "You do not have permission to access this page!!!"
      redirect_to root_path
    end
  end

  # no new
  def new
  end

  def create
    @question = Question.new(params.require(:questions).permit(:question))
    @question.user = @user
    if @question.save
      flash[:notice] = "You question has been submitted"
    else
      flash[:error] = "There was a error with uploading your question. Please try again later"
    end
      redirect_to user_path(@user)
    # p @question
  end

  def update
    @question = Question.find_by_id(params[:id])
    data = params.require(:question).permit(:answer)
    if ( @question.update_attribute(:answer, data[:answer]) )
      redirect_to user_unanswered_questions_path
    end
  end

  # maybe
  def show
  end

  def destroy
  end

  private
  def set_user
    @user = User.find(params[:user_id])
  end

  # def question_params
  #   params.require(:questions).permit(:question)
  # end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :redirect_signed_in, only: [:create, :new]

  def new
    @user = User.new
  end

  def create
    @user = User.confirm(session_params)
    if @user
      login(@user)
      redirect_to @user
    else
      flash[:error] = 'Incorrect email or password'
      redirect_to login_path
    end
  end

  def destroy
    logout
    flash[:notice] = "Successfully logged out"
    redirect_to root_path
  end

  private
  def session_params
    params.permit(:email, :password)
  end

  def redirect_signed_in
    if current_user
      redirect_to user_path(current_user)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_signed_in, only: [:create, :new]
  before_action :set_page, only: [:index, :show]


  def index
    @users = User.all

    @pages = Paginator.new(@users, 12)
    @page = @pages[ @page_number ]
    @page = @page ? @page.elements : []

    @url = Addressable::Template.new( "/users{?page}")

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.welcome_email(@user).deliver_now
      login(@user)
      redirect_to @user
    else
      flash[:error] = 'There was a problem with Signing you up. Please try again later.'
      redirect_to new_user_path
    end
  end

  def show
    user_id = params[:id]

    @user = User.find(user_id)
    @logged_in = is_signed_in? @user
    @question_list = @user.questions.where.not(answer: nil)

    @pages = Paginator.new(@question_list, 5)
    @page = @pages[ @page_number ]
    @page = @page ? @page.elements : []

    @url = Addressable::Template.new( "#{user_path(@user)}{?page}")

  end

  def edit
  end

  def update
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end

  def set_page
    @page_number = params[:page].nil? ? 1 : params[:page].to_i
  end

  def redirect_signed_in
    if current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  FLASH_COLOR_SCHEME = {
    error: "red",
    notice: "green"
  }

  def flash_color_for(name)
    FLASH_COLOR_SCHEME[name.to_sym]
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def logout
    @current_user = session[:user_id] = nil
  end

  def is_signed_in?(user)
    current_user and (current_user.id === user.id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l4 m4 s4 left-align">
        <h5 class="white-text">Company</h5>
        <ul>
          <li>About</li>
          <li>Jobs</li>
          <li>Press</li>
          <li>News</li>
        </ul>
      </div>

      <div class="col l4 m4 s4 center-align">
        <h5 class="white-text">Communities</h5>
        <ul>
          <li>Developers</li>
          <li>Students</li>
        </ul>
      </div>

      <div class="col l4 m4 s4 right-align">
        <h5 class="white-text">Our Code</h5>
        <ul>
          <a class="grey-text text-lighten-3" target='_blank' href="https://github.com/SrishtiSehtia/develop_me"><i class="fab fa-github fa-3x"></i></a>
          <li><a class="grey-text text-lighten-3" target='_blank' href="https://github.com/SrishtiSehtia">Srishti</a></li>
          <li><a class="grey-text text-lighten-3" target='_blank' href="https://github.com/TheForce88">Elaine</a></li>
          <li><a class="grey-text text-lighten-3" target='_blank' href="https://github.com/marcellino-ornelas">Marcellino</a></li>
          <li><a class="grey-text text-lighten-3" target='_blank' href="https://github.com/passion-pixel">Natalie</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container center-align">
    © 2018 Copyright ShredX
    </div>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<div class="navbar-fixed">
  <nav>
    <div class="nav-wrapper">
      <a href="#!" class="brand-logo">DevelopMe</a>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="fa fa-bars"></i></a>
      <ul class="right hide-on-med-and-down">
         <li><%= link_to "Home", root_path %> </li>
        <li><a href="/users">Mentors</a></li>
        <% if current_user %>
          <li> <%= link_to "Profile", user_path(current_user) %> </li>
          <li><%= link_to "Sign Out", logout_path %></li>
        <% else %>
          <li> <%= link_to "Log In", login_path %> </li>
          <li><%= link_to "Sign Up", new_user_path %></li>
        <% end %>
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <li> <%= link_to "Home", root_path %> </li>
        <li><a href="/users">Mentors</a></li>
        <% if current_user %>
          <li> <%= link_to "Profile", user_path(current_user) %> </li>
          <li><%= link_to "Sign Out", logout_path %></li>
        <% else %>
          <li> <%= link_to "Log In", login_path %> </li>
          <li><%= link_to "Sign Up", new_user_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DevelopMe</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
</head>

<body>

  <%= render "layouts/nav" %>

  <% flash.each do |name, msg| %>
    <% color = flash_color_for(name) %>
    <div class="card-panel <%= color %> lighten-5 <%= color %>-text text-darken-3"> <%= msg %> </div>
  <% end %>

  <main>
    <%= yield %>
  </main>

  <%= render "layouts/footer" %>

  <div class="sidenav-overlay"></div>
  <div class="drag-target"></div>
</body>
</html>

app/views/main/home.html.erb
<script type="text/javascript">
  $(document).ready(function(){
      $('.parallax').parallax();
    });
</script>

<div class="parallax-container">
  <div class="parallax"><%= image_tag "/assets/images/web-designer-pune-background.jpg" %></div>
  <div class="section no-pad-bot" id="index-banner">
    <div class="container">
      <br />
      <br />
      <h1 class="header center teal-text"> Develop Me</h1>
      <div class="row center">
        <h3 class="header col s12 light"> Build your Developer Community</h3>
        <p>Choose from web developers, community leaders, industry experts to answer your development questions!</p>
      </div>

      <div class="row center">
      <% if !current_user %>
        <a href="/users/new" id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Get Started</a>
        <a href="/login" id="download-button" class="btn-large waves-effect waves-light orange">Log in</a>
        <br />
      <% end %>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="section">
    <div class="row">
      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center light-blue-text"> <i class="fas fa-bolt"></i> </h2>
          <h5 class="center">Get Answers from Web Developers</h5>
          <p class="light">We created a platform for you to be able to ask people in the field specific technical or career related questions with an application that allows you to connect with a community of professionals in the field. Additionally, we created an application that allows a soother experience for developers who need their questions answered.</p>
        </div>
      </div>
      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center light-blue-text">
            <i class="fas fa-users"></i>
          </h2>
          <h5 class="center">User Experience Focused</h5>
          <p class="light">
            By utilizing elements and principles of Web Development, we were able to create a platform that allows for developers to connect with each other in an easy to use application.
          </p>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center light-blue-text">
            <i class="fas fa-cogs"></i>
          </h2>
          <h5 class="center">Easy to work with </h5>
          <p class="light">
            We have provided detailed documentation as well as specific code examples to help new users get started. We are also always open to feedback and can answer any questions a user may have about Materialize.
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="parallax-container valign-wrapper">
  <div class="parallax"><%= image_tag "/assets/images/web_dev_rainbow.jpg" %></div>
  <div class="section no-pad-bot">
    <div class="container">
      <div class="row center">
        <h5 class="header col s12 light">.Ω</h5>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="section">

    <div class="row">
      <div class="col s12 center">
        <h3><i class="mdi-content-send brown-text"></i></h3>
        <h4>Meet the Team</h4>
        <p class="center-align light">We are a team of web developers working to create our app, Develop Me.</p>
      </div>
    </div>
  </div>
</div>



<div class="container">
  <div class="section">
      <!-- This the Icon Section -->
    <div class="row">
      <div class="col s12 m3">
        <div class="icon-block">
          <h2 class="center light-blue-text"> <i class="material-icons">    </i>
            <%= image_tag "/assets/images/elaineprofilepic.jpg", class:"profilepic" %> </h2>
          <h5 class="center">Elaine</h5>
          <p class="center light">
            Web Developer
            <br />
            <div class="center-align">
              <a class="black-text text-lighten-3" target='_blank' href="https://www.linkedin.com/in/elainechesoni/"><i class="center-align fab fa-linkedin fa-3x"></i></a>
            </div>
          </p>

        </div>
      </div>
      <div class="col s12 m3">
        <div class="icon-block">
        <h2 class="center light-blue-text">
          <i class="material-icons">    </i>
          <%= image_tag "/assets/images/srishtiprofilepic.jpg", class:"profilepic" %>
        </h2>
        <h5 class="center">Srishti</h5>
        <p class="center light">
          Web Developer
          <br />
          <div class="center-align">
            <a class="black-text text-lighten-3" target='_blank' href="https://www.linkedin.com/in/srishtisehtia/"><i class="center-align fab fa-linkedin fa-3x"></i></a>
          </div>
        </p>
        </div>
      </div>

      <div class="col s12 m3">
        <div class="icon-block"></div>
        <h2 class="center light-blue-text">
          <i class="material-icons">    </i>
          <%= image_tag "/assets/images/nataliepic.jpg", class:"profilepic" %>
        </h2>
        <h5 class="center">Natalie</h5>
        <p class="center light">
          Web Developer
          <br />
          <div class="center-align">
            <a class="black-text text-lighten-3" target='_blank' href="https://www.linkedin.com/in/nataliecontreras/"><i class="center-align fab fa-linkedin fa-3x"></i></a>
          </div>
        </p>
      </div>

      <div class="col s12 m3">
        <div class="icon-block">
        <h2 class="center light-blue-text">
          <i class="material-icons">    </i>
          <%= image_tag "/assets/images/marcellinoprofilepic.jpg", class:"profilepic" %>
        </h2>
        <h5 class="center">Marcellino</h5>
        <p class="center light">
          Web Developer
          <br />
          <div class="center-align">
            <a class="black-text text-lighten-3" target='_blank' href="https://www.linkedin.com/in/marcellino-ornelas/"><i class="fab fa-linkedin fa-3x"></i></a>
          </div>
        </p>
        </div>
      </div>

    </div>
  </div>
</div>




<div class="parallax-container">
  <div class="parallax"><%= image_tag "/assets/images/blue-white-dots.png" %></div>
</div>
<h3 class="center-align">Contact Us</h3>
<div class="row">
  <div class="col s1 m1 l3"></div>
  <%= form_with(scope: :email, url: '/contact_us', local:true, class:"col s10 m10 l6") do |form| %>
    <div class="row">
      <div class="input-field col s12 m6">
        <%= form.label :first_name %>
        <%= form.text_field :first_name, required: true, class:"validate" %>
      </div>

      <div class="input-field col s12 m6">
        <%= form.label :last_name %>
        <%= form.text_field :last_name, required: true, class:"validate" %>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s12">
        <%= form.label :email %>
        <%= form.email_field :email, required: true, class:"validate" %>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s12">
        <%= form.label :message %>
        <%= form.text_field :message, required: true, class:'validate' %>
      </div>
    </div>

    <div class="col s12 center-align materialize-textarea">
      <%= form.submit 'send', class:'btn waves-effect waves-light row' %>
    </div>

  <% end %>
  <div class="col s1 m1 l3"></div>

</div>





      </div>
    </div>
  </div>

app/views/pagination/_pagination.html.erb
<% if total_pages > 1 %>
  <ul class="pagination center">
    <% if (page_number - 1) > 0 %>
      <li>
        <%= link_to url.expand(page: page_number - 1).to_s do %>
          <i class="fa fa-angle-left"></i>
        <% end %>
      </li>
    <% end %>

    <% (1..total_pages).each do |number| %>
      <li class="waves-effect"><%= link_to number, url.expand(page: number).to_s %></li>
    <% end %>

    <% if (page_number + 1) <= total_pages %>
      <li>
        <%= link_to url.expand(page: page_number + 1).to_s do %>
          <i class="fa fa-angle-right"></i>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/questions/_question_list.html.erb
<ul class="collapsible popout" data-collapsible="accordion">
  <% question_list.each do |question| %>
    <li>
      <div class="collapsible-header teal-text"><%= question.question %></div>
      <div class="collapsible-body"><span><%= question.answer %></span></div>
    </li>
  <% end.empty? and begin %>
    <h3> There are no questions at this time</h3>
  <% end %>
</ul>

app/views/questions/new.html.erb
<h1>Questions#new</h1>
<p>Find me in app/views/questions/new.html.erb</p>

app/views/questions/show.html.erb
<h1>Questions#show</h1>
<p>Find me in app/views/questions/show.html.erb</p>

app/views/questions/unanswered_questions.html.erb
<!--breadcrumbs start-->
<div id="breadcrumbs-wrapper" class="grey lighten-3 section">
  <div class="container" style="text-align:center;">
    <div class="row">
      <div class="col s12">
        <h3 class="breadcrumbs-title grey-text text-darken-2"><i>People Are Asking...</i></h3>
        <a href="#!" class="breadcrumb teal-text">By Date</a>
        <a href="#" class="breadcrumb teal-text">By Topic</a>
        <a href="#" class="breadcrumb teal-text">By Frequency</a>
      </div>
    </div>
  </div>
</div>
<!--breadcrumbs end-->

<div class="intro">
  <p class="grey-text text-darken-2" style="text-align:center;"><i>You will find the questions people have personally asked you listed below. Click on the question to answer. Questions will not be posted on your profile until they have been answered.</i></p>
</div>

<ul class="collapsible popout" data-collapsible="accordion">
  <% @page.each do |question| %>
    <li>
      <div class="collapsible-header grey-text text-darken-2"> <%= question.question%> </div>
      <div class="collapsible-body">
        <%= form_with(model: question, url: user_question_path(@user,question), local:true) do |form| %>
          <div class="input-field">
            <%= form.label :answer %>
            <%= form.text_field :answer %>
          </div>
          <div class="actions" style="text-align:center;">
            <%= form.submit "Submit Answer", class: "waves-effect waves-light btn"%>
          </div>
        <% end %>
      </div>
    </li>
  <% end %>
</ul>
<div class="section">
  <%= render "pagination/pagination", page_number: @page_number , url: @url ,total_pages: @pages.total_pages %>
</div>

app/views/users/index.html.erb
<div class="header">
    <div class="header-wrapper db">
      <div class="header-title" style="text-align:center;">
        <h1 class="blue-text">Mentors+</h1>
        <!-- Dropdown Trigger -->
        <a class='dropdown-button btn' href='#' data-activates='dropdown1' style="text-align:center;">Filter By</a>
        <!-- Dropdown Structure -->
        <ul id='dropdown1' class='dropdown-content'>
          <li><a href="#!">one</a></li>
          <li><a href="#!">two</a></li>
          <li><a href="#!">three</a></li>
          <li><a href="#!">four</a></li>
          <li><a href="#!">five</a></li>
        </ul>
      </div>
    </div>
    <!-- Fixed Masonry Filters -->
    <div class="categories-wrapper af lighten-1"></div>
</div>
    <!-- Gallery -->
  <div>
    <div id="gallery">
      <div class="profile-container" style="display:flex; justify-content:space-around;">
      <div class="profile-container">

        <div class="profile-cards">
          <div class="gallery-item custom-container">

            <div class="row custom-container">
            <% @page.each do |user| %>
                  <div class="col s12 m3 l3 custom-spacing">
                    <div class="card blue-grey darken-1">

                    <div class="card-image">
                      <img src="/assets/images/empty_profile.jpg">
                    </div>

                    <div class="card-content white-text">
                      <span class="card-title"><%= user.full_name %></span>
                      <p>A little about me...</p>
                    </div>
                    <div class="card-action">
                      <%= link_to "View", user_path(user) %>
                      <a href="#">This is a link</a>
                    </div>
                  </div>
                </div>
          <% end %>
        </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="section">
  <%= render "pagination/pagination", page_number: @page_number , url: @url ,total_pages: @pages.total_pages %>
</div>

app/views/users/new.html.erb
<h1 class='center-align'>Sign Up</h1>

<div class="row">
  <div class="col s1 m1 l3"></div>
  <%= form_with(model: @user, local:true, class:"col s10 m10 l6") do |form| %>
    <div class="row">
      <div class="input-field col s12 m6">
        <%= form.label :first_name %>
        <%= form.text_field :first_name, required: true, class:"validate" %>
      </div>

      <div class="input-field col s12 m6">
        <%= form.label :last_name %>
        <%= form.text_field :last_name, required: true, class:"validate" %>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s12">
        <%= form.label :email %>
        <%= form.email_field :email, required: true, class:"validate" %>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s12">
        <%= form.label :password %>
        <%= form.password_field :password, required: true, minlength: 5, class:"validate" %>
      </div>
    </div>

    <div class="col s12">
      <%= form.submit 'save', class:'btn waves-effect waves-light row' %>
    </div>

  <% end %>
  <div class="col s1 m1 l3"></div>

</div>

app/views/users/show.html.erb
<div class="container">
  <div class="section">
    <div class="section">
      <h2 class="center-align"><%= @user.full_name %></h2>
    </div>
    <div class="divider"></div>

    <% if @logged_in %>
      <div class="section">
        <%= link_to "Unanswered Questions", user_unanswered_questions_path(@user), class:"btn" %>
      </div>
    <% else %>
      <h4 class="teal-text">Having a problem?</h4>
      <p> Ask a question to <%= @user.first_name %> and let him personally respond to you </p>
      <%= form_with(scope: :questions, url: user_questions_path(@user) ,local: true) do |form| %>
        <div class="row">
          <div class="col s11">
            <div class="input-field">
              <%= form.label :question  %>
              <%= form.text_field :question, required:true, class:"validate" %>
            </div>
          </div>
          <div class="input-field col s1">
            <%= form.submit "Ask", class:" waves-effect waves-light btn" %>
          </div>
        </div>
      <% end %>
    <% end %>
    <%= render "questions/question_list", question_list: @page %>

    <%= render "pagination/pagination", page_number: @page_number , url: @url ,total_pages: @pages.total_pages %>
  </div>
</div>

<% count = @user.questions.where(answer: nil).count %>
<% if @logged_in && params[:page].nil? && !count.zero? %>
  <script type="text/javascript">
    $(function(){
      Materialize.toast('You have <%= count %> questions that need to be answered', 8000)
    });
  </script>
<% end %>